#!/bin/bash

# Script is called by strap for setting up the dotfiles

set -euo pipefail
set -vx
echo "moving dotfiles for chezmoi..."

# relocate the checkout to the usual ~/Projects/private/dotfiles location
[[ -d ~/Projects/private ]] || mkdir -p ~/Projects/private
[[ -d ~/Projects/private/dotfiles ]] || mv ~/.dotfiles ~/Projects/private/dotfiles

# link the conventional .dotfiles location
[[ -L ~/.dotfiles ]] || ln -sf ~/Projects/private/dotfiles ~/.dotfiles

# link the chezmoi ~/.local/share/chezmoi location
[[ -d ~/.local/share ]] || mkdir -p ~/.local/share
[[ -L ~/.local/share/chezmoi ]] || ln -sf ~/Projects/private/dotfiles ~/.local/share/chezmoi

echo "prepare chezmoi..."
[[ "$(command -v chezmoi)" ]] || brew install chezmoi

chezmoi init
